### ISSUE TITLE
Contributors documentation guide

### ISSUE THREAD

**Issue by esakal** [mrjono1/joi-to-typescript#111]
Hello @mrjono1, Thanks again for contributing joi-to-typescript to the community. 

Do you have documentation about the generation flows and data structures that contributors can learn from when they work on a contribution? I saw in the readme the contribution section but it doesn't deal with documentations. 

Thanks
Eran

**Comment by mrjono1** [comment]
Hi

I don't have anything like that, it sounds nice but I doubt I would get around to doing it.

Cheers
Jono

**Comment by esakal** [comment]
Thanks :)
