### ISSUE TITLE
Use unknown instead of any

### ISSUE THREAD

**Issue by mike-marcacci** [mrjono1/joi-to-typescript#113]
Thanks for the great project! I've noticed that in all cases where this library writes the type `any`, the type `unknown` would be preferred. Was this intentional, or would you be open to a PR that changed this behavior? [Here is a solid explanation of the difference.](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#new-unknown-top-type)

**Comment by mrjono1** [comment]
Hi @mike-marcacci 
your probably right, I hadn't thought about it much

**Comment by mrjono1** [comment]
I think you are correct that the rest of the time that `any` is generated it should probably be `unknown` instead. 

I came up with a few scenarios

Scenario 1
Current
Joi.Object().unknown(true) => [x: string]: any
Proposed
Joi.Object().unknown(true) => [x: string]: unknown
I like this one
looks good https://github.com/mrjono1/joi-to-typescript/tree/unknown

Scenario 2
Current
property: Joi.Array() => property: any[]
Proposed 
property: Joi.Array() => property: unknown[] 
This seems good to me

Scenario 3
Current
property: Joi.Any() => property: any
Proposed?
property: Joi.Any() => property: unknown

Scenario 4
Current
property: Joi.Object() => property: object
Proposed?
property: Joi.Object() => property: unknown

@mike-marcacci  what do you think about these scenarios?

**Comment by mrjono1** [comment]
I have just released the changes I mentioned above

**Comment by mrjono1** [comment]
I have made some changes and woth no feedback from the OP I'm closing this
