### ISSUE TITLE
More flexible file system API

### ISSUE THREAD

**Issue by mo4islona** [mrjono1/joi-to-typescript#133]
Hi there, first of all thanks for a great job so far!

The library works fine with a one directory that have only one directory with joi schemas
But it is not really comfortable otherwise, especially if you have dozen of joi schemas and complex structure  in your project

What about breaking major changes in API? why not to use `glob` in search joi schema files? 

```ts
const defaultOutputFile = (srcPath: string, fileName: string) =>  path.join(
     srcPath, 
    `${path.basename(fileName, '.ts')}.type.ts`
)

export function convertFromDirectory({
    schemaFile,
    outputFile = defaultOutputFile,
    // ...
}{
    schemaFile: string | string[];
    outputFile?: (scrPath: string, fileName: string) => string
    // ...
}) {
    // ... implementation
} 
```

**Benefits** 
The usage is more flexible and fits more use cases.
Below old options can be dropped from API because it could be done by this new realisation

1) `schemaFileSuffix`
```ts
 convertFromDirectory({
    schemaFile: './src/**/*.schema.ts',
    outputFile: (srcPath: string, fileName: string) => path.join(srcPath, fileName.replace('.schema', '')),
}})
```

2) `flattenTree `
```ts
convertFromDirectory({
    schemaFile: './src/**/*.schema.ts',
    outputFile: (srcPath: string, fileName: string) => path.join('./src/types', fileName),
}})
```

3) `rootDirectoryOnly `
```ts
convertFromDirectory({
    schemaFile: './src/*.schema.ts',
}})
```

4) `ignoreFiles` can be be done by glob in a variety of ways out of box

**Caveats**
I am not sure about  `indexAllToRoot` — it could be hard to implement

What do you think? Will you accept such PR?

**Comment by mrjono1** [comment]
Searching a project to find schemas would be great.
I actually use a crude implementation of what you propose to search for Schema folders instead of a file suffix, using glob is also probably faster than using fs.

**Comment by mrjono1** [comment]
I'm not sure how many people use indexAllToRoot. It might not be a popular opinion

**Comment by mrjono1** [comment]
Hey @mo4islona I'm curious if you had a chance to look at your suggestion?

**Comment by mo4islona** [comment]
Sure. 

Dont had much time for work but  enough to implement  basic features

https://github.com/mo4islona/joi-to-typescript/pull/1

the progress of tests 

- none ✅
- primitives types ✅
- multiple file - I ve stacked here 😩

I have a problem if schemas names will have a collisions (that i have in my own project) of external schemas names and physical file paths
To resolve it we must known from what source file path is schema imported (which seems to be a very complicated)

Looking for a solution.

**Comment by mrjono1** [comment]
Thankyou I'll see if i can help

**Comment by mrjono1** [comment]
Stale
