### ISSUE TITLE
Handling of function type- 

### ISSUE THREAD

**Issue by bhanuc** [mrjono1/joi-to-typescript#148]
Nice module, though I was facing an issue while using the function type.  
So while converting joi schema `  push: j.function().required() ` to typescript type using this module leads to  
` push?: (...args: any[]) => any; `   
whereas the correct output should be  ` push: (...args: any[]) => any; `

**Comment by mrjono1** [comment]
yep sounds like an issue where functions don't respect the required option

**Comment by mrjono1** [comment]
I just looked though my notes and looks like `.function()` hasn't been supported yet but somehow works most of the time, should be easy to add

**Comment by mrjono1** [comment]
https://github.com/mrjono1/joi-to-typescript/pull/149 looks like the issue can affect a few things

**Comment by mrjono1** [comment]
resolved https://github.com/mrjono1/joi-to-typescript/releases/tag/2.2.2
