### ISSUE TITLE
Error when sourcing from a directory from another ES module package

### ISSUE THREAD

**Issue by shennan** [mrjono1/joi-to-typescript#158]
I want to be able to build from schemas in another package (separate from the package where the destination interfaces are built and written to). Currently this doesn't seem to be possible as the other package has `"type": "module"` in its' `package.json` file.

The resulting error is thus:

```
(node:39837) UnhandledPromiseRejectionWarning: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/some-other-package/src/schemas/OneSchema.ts
require() of ES modules is not supported.
require() of /Users/some-other-package/src/schemas/OneSchema.ts from /Users/my-types-package/node_modules/joi-to-typescript/dist/analyseSchemaFile.js is an ES module file as it is a .ts file whose nearest parent package.json contains "type": "module" which defines all .ts files in that package scope as ES modules.
Instead change the requiring code to use import(), or remove "type": "module" from /Users/some-other-package/package.json.
```

Removing `"type": "module"` from said package does indeed squash the error, but that is sub-optimal as this package is required by others and should be an ES module package.

Is there any way of resolving this?

My build code is basically the same as your example, except I've plonked your source schemas into the "other" package:

```
const result = await convertFromDirectory({
    schemaDirectory: '../some-other-package/src/schemas',
    typeOutputDirectory: './lib/built',
    debug: true
  })
```

Thanks in advance for any help.

**Comment by LukeShay** [comment]
This should be resolved once you make the next release.

**Comment by mrjono1** [comment]
this should now be resolved with version 3.x
