### ISSUE TITLE
How do I add complex types to `unknownType`?

### ISSUE THREAD

**Issue by vamcs** [mrjono1/joi-to-typescript#168]
When creating a dictionary that has a more complex type than primitives, for example another schema, how can I correctly add that type reference?

For example, my simplified case below:

```typescript
export const Item = Joi.object({ id: Joi.string().required() })
export const Items = Joi.object().unknown(true).meta({ unknownType: 'Array<Item>' })
```

`Items` is a dictionary where each entry is list of `Item`. This works fine for the generated file for these types, since `Item` is after all defined there. But if I use `Items` in another schema, `Array<Item>` will be wrong since the import will be missing (or a copy of the type itself).

**Comment by mrjono1** [comment]
whats the output you get when running this?

**Comment by vamcs** [comment]
@mrjono1 oh I didn't see you replied, thanks though :) 

In this example, I would get:
```typescript
interface Item = {
  id: string
}

interface Items = {
  [x: string]: Array<Item>
}
```

But if I use `Items` in another schema, the `Item` won't follow, since it's just a string. Like: 
```typescript
const AnotherSchema = Joi.object({ items: Items.required() }) 
```

The generated output would be:
```typescript
interface AnotherSchema = {
  items: {
   [x: string]: Array<Item>
  }
}
```

And TS would complain since we're not importing `Item`.

**Comment by vamcs** [comment]
@mrjono1 I've create a PR to extend the type assertion: https://github.com/mrjono1/joi-to-typescript/pull/173. I hope this implementation makes sense.

**Comment by mrjono1** [comment]
This has been resolved and released
