### ISSUE TITLE
Converting schema marked with `className` meta property ignores schema extension

### ISSUE THREAD

**Issue by DBachiloVironit** [mrjono1/joi-to-typescript#169]
I noticed an unfortunate behavior when extending renamed schemas. Here is a small example.

### With meta

Source schemas:
```
export const BaseSchemaBar = Joi.object({
    bar: Joi.number().required()
}).meta({ className: 'BaseSchemaDTO' });

export const BaseExtensionSchema = Joi.object({
    baz: BaseSchemaBar.keys({
        foo: Joi.boolean().required()
    })
}).meta({ className: 'BaseExtensionDTO' });
```

Resulted interfaces:
```
export interface BaseSchemaDTO {
    bar: number;
}

export interface BaseExtensionDTO {
    baz: BaseSchemaDTO;
}
```

As you can see, `foo` property is missing.

### Without meta

Source schemas:
```
export const BaseSchemaBar = Joi.object({
    bar: Joi.number().required()
});

export const BaseExtensionSchema = Joi.object({
    baz: BaseSchemaBar.keys({
        foo: Joi.boolean().required()
    })
});
```

Resulted interfaces:
```
export interface BaseSchemaBar {
  bar: number;
}

export interface BaseExtensionSchema {
  baz: {
    bar: number;
    foo: boolean;
  };
}
```

Here all fields are fine.

**Comment by mrjono1** [comment]
This sounds like a tricky one, what is happening is the first one finds meta and stops processing, the second finds no class name and keeps going.
So the function that finds the className needs to also check if there are any extra properties if there is don't return a className

**Comment by lOlbas** [comment]
Hey @mrjono1, I've tested this bug after noticing that https://github.com/mrjono1/joi-to-typescript/pull/235 was merged, but it seems to only work when `Joi.keys()` is top level action, i.e. `export const BaseExtensionSchema = BaseSchemaBar.keys({ ... });`, it still doesn't work with the example in this issue. Is it known problem?
