### ISSUE TITLE
Do not convert index.ts in schemaDirectory [Question]

### ISSUE THREAD

**Issue by hazmah0** [mrjono1/joi-to-typescript#18]
I would like to have an `index.ts` in the `schemaDirectory` that exports all Joi schemas without `joi-to-typescript` trying to convert it.

The reason for this is because an `index.ts` allows me to easily import the Joi schemas elsewhere in the code base without the need for one import statement per schema.

**Comment by InfinitySamurai** [comment]
I might give this one a crack if maintainers think it's good. I reckon this should have a setting associated with it, defaulted to ignore the index.ts as well. Something like `"ignoreIndexFiles" = true` by default

**Comment by mrjono1** [comment]
Sounds good 👍

**Comment by mrjono1** [comment]
or should the setting could be something like `ignoreFiles = ['index.ts', 'subDir/ingoreSchema.ts']` ?

**Comment by InfinitySamurai** [comment]
Yeah sounds reasonable. I'm not sure how pattern matching or wildcards work but I'm sure I can sort something out

**Comment by mrjono1** [comment]
Changed merged just needs releasing

**Comment by mrjono1** [comment]
released under v1.10.0
