### ISSUE TITLE
Generating data type based on custom type's base type?

### ISSUE THREAD

**Issue by brutus-law** [mrjono1/joi-to-typescript#205]
We have some custom types we're using (Mainly to control the value format in a consolidated place)

An example:

```
export const Joi = Joi.extend(joi => {
    return {
      type: 'time',
      base: joi.string().pattern(/^\d{2}:\d{2}:\d{2}-\d{4}$/),
    };
  })
```

```
const UserSchema = Joi.object({
  name: Joi.string().required(),
  timeSubmitted: Joi.time().required()

})
```

But it's getting generated as this:
```
interface UserSchema {
  name: string;
  time: unknown;
}
```

Is there a way to generate `time` as a string since that's its base type?

**Comment by mrjono1** [comment]
I think this is possible there is a function that gets the type, using this example I should be able to figure this out

**Comment by malhotraamit236** [comment]
@mrjono1 wouldn't `meta` be able to solve this?

**Comment by mrjono1** [comment]
As a very simple workaround yes it would

**Comment by malhotraamit236** [comment]
Thanks!

**Comment by brutus-law** [comment]
How would the meta property look? Are we saying there'd be the Joi config type and then a duplicate type added as a meta prop? Cause that seems highly likely to get outta sync if someone doesn't update both.

**Comment by mrjono1** [comment]
This should do it
```TypeScript
const UserSchema = Joi.object({
  name: Joi.string().required(),
  timeSubmitted: Joi.time().required().meta({ className: 'string'} )
})
```

**Comment by brutus-law** [comment]
@mrjono1 Thats what I was afraid of. If time() for some reason or another changes from extending string to extending number at some point future, you could miss changing this and then you have a type deviation.

**Comment by brutus-law** [comment]
Finally got around to testing on the extend stuff. Looks like you can do meta in the extend portion and it carries over to all the instances:

```
Joi.extend(joi => {
    return {
      type: 'year',
      base: joi.number().integer().min(0).meta({ className: 'number' }),
    };
  })
```

So that works for the immediate. Would be nice if it could assume it based on what base type you set but nice to have at this point when there's time to add it.
