### ISSUE TITLE
Expected Joi.allow(null) to only allow null values

### ISSUE THREAD

**Issue by lukebelbina** [mrjono1/joi-to-typescript#206]
Consder the following code:

```javascript
export const ExampleSchema = Joi.object({
  a: Joi.allow(1).required(),
}).meta({ className: 'Example' });`

// This generates what I would expect on the TS interface side:

export interface Example {
  a: 1;
}
```

However when I try for only a null value it works differently:

```javascript
export const ExampleSchema = Joi.object({
  a: Joi.allow(null).required(),
}).meta({ className: 'Example' });`

// generates

export interface Example {
  a: any | null;
}
```

Is this a bug or intended behavior? If it is intended is there a way I can define a property on a schema to always expect to be null?

**Comment by lukebelbina** [comment]
Hi @mrjono1 , do you consider this a bug? If so, do you expect you have a quick fix or would you like for me to try and fix it and PR?

**Comment by mrjono1** [comment]
I've tagged this as a bug, I'm happy for any pull requests

**Comment by mrjono1** [comment]
https://github.com/mrjono1/joi-to-typescript/pull/315 how does this look?
