### ISSUE TITLE
updated to 4.0.0 - logging LOTS of json to the console

### ISSUE THREAD

**Issue by kingmesal** [mrjono1/joi-to-typescript#219]
Picked up the latest, and the output to console is tons of JSON. I made sure debug: false, but still all the output is in JSON.

{"type":"string","flags":{"description":"end segment of url for this page","presence":"required"},"rules":[{"name":"min","args":{"limit":1}},{"name":"max","args":{"limit":100}},{"name":"case","args":{"direction":"lower"}},{"name":"pattern","args":{"regex":"/^[a-z0-9]+(?:-[a-z0-9]+)*$/"}}],"metas":[{"className":"SlugValue"}]}
{"type":"string","rules":[{"name":"uri"}]}
{"type":"string","rules":[{"name":"uri"}],"metas":[{"className":"ImageValue"}]}
{"type":"string","rules":[{"name":"uri"}],"metas":[{"className":"ImageValue"}]}
{"type":"date","flags":{"format":"javascript"}}
{"type":"date","flags":{"format":"javascript"},"metas":[{"className":"DateValue"}]}
{"type":"date","flags":{"format":"javascript"},"metas":[{"className":"DateValue"}]}
{"type":"string"}
{"type":"string","metas":[{"className":"NoValueRecord"}]}

**Comment by mrjono1** [comment]
Yeah somehow a console.log made it in, I'll  fix this up and look at the lint rules

**Comment by mrjono1** [comment]
fix released under 4.0.1
