### ISSUE TITLE
Bug when files in different directories have the same name.

### ISSUE THREAD

**Issue by drico** [mrjono1/joi-to-typescript#227]
When 2 schema files have same name in different directories, only the first one generates an interface file.

example : 
````
- schemas
   - folder1
      -  mySchema.ts
      -  mySchema2.ts
   - folder2
      -  mySchema.ts
      -  mySchema3.ts
````
generates the following interfaces : 

````
- interfaces
   - folder1
      -  mySchema.ts
      -  mySchema2.ts
   - folder2
      -  mySchema3.ts
````
=> `interfaces/folder2/mySchema.ts` is missing.

**Comment by mrjono1** [comment]
Hi, this is by design so that it can create an index file.
But there is options to make it work the way u want

**Comment by drico** [comment]
Ok I understand. But then, what is the option you're talking about ?

**Comment by mrjono1** [comment]
you can run this project on directory folder1 and folder2 instead of the root directory
