### ISSUE TITLE
Using variables for schemas

### ISSUE THREAD

**Issue by Kaseano** [mrjono1/joi-to-typescript#228]
Hello, wondering what's happening here with the [object Object] output:

**demoSchema.ts**
```typescript
import Joi from "joi";

const foo = Joi.object({ bar: "baz" })

export const demoSchema = Joi.object({ foo })
	.meta({ className: "demo" })
```

**emitted demo.ts**
```typescript
export interface demo {
  foo?: {
    bar?: [object Object] | 'baz';
  };
}

```

**Comment by mrjono1** [comment]
If you export foo as well it should work

**Comment by mrjono1** [comment]
Does this validate an object? It doesnt look like valid joi

**Comment by mrjono1** [comment]
Something like this might be what you are after? (I havent tested this)
```TypeScript
import Joi from "joi";

const foo = Joi.object({ bar: "baz" })

export const demoSchema = foo.keys()
	.meta({ className: "demo" })
```

**Comment by Kaseano** [comment]
Sorry! You're absolutely right that isn't valid joi.  I'll close this.
