### ISSUE TITLE
Handle basic uses of `.when()`

### ISSUE THREAD

**Issue by JRMurr** [mrjono1/joi-to-typescript#24]
I think we could support simple use cases of when like 
```typescript
Joi.object({
      type: Joi.boolean().valid(true, false),
      trueField: Joi.string().when('type', {
        is: true,
        then: Joi.required(),
        otherwise: Joi.forbidden()
      }),
      falseField: Joi.string().when('type', {
        is: false,
        then: Joi.required(),
        otherwise: Joi.forbidden()
      })
    })
```
this would support an object like `{
  type: false,
  falseField: 'aStr'
}` and `{
  type: true,
  trueField: 'aStr'
}` and would error on something like `{
  type: false,
  trueField: 'shouldNotWork'
}`

Right now the lib would make a type like 

`{type: true | false; trueField: string; falseField: string} ` which is correct but could be better

Under the hood joi uses references to figure out what field to look at and generate a good validator. There can be a lot of runtime stuff references can use but i think simple sibling key references could be supported. Handling a reference to a grand parent object is probably too much at the moment. 

I think if we support a simple case like this then fall back to what we do now if the reference/is condition is too complicated would be nice.

**Comment by JRMurr** [comment]
The example I mentioned here could probably work if it was switched to alternatives but at least in the code base i contribute too we have a lot of schemas like this

**Comment by mrjono1** [comment]
humm, probably need to start with supporting forbidden, that should be easy

**Comment by JRMurr** [comment]
Yea i think it will too, im working on branch right now that will hopefully have this basic case supported along with forbidden

**Comment by mrjono1** [comment]
I think we could make this package generate a type like this? or is forbidden something else?
```javascript
{
  type: boolean;
  trueField?: string;
  falseField?: string;
}
```

**Comment by mrjono1** [comment]
ahh I now understand what you have proposed, my was is very simple. Your way is better but could be hard

**Comment by JRMurr** [comment]
Yea i think forbidden only really is useful for `when` since it just removes that field as a valid option. My current plan is a check in the object parsing to see if any fields reference other keys, then make a discriminated union of all the cases. Easier said then done lol

**Comment by mrjono1** [comment]
it sounds like joi.describe() may strip out a bit of the information you need? hopefully you dont need to access the internal joi properties

**Comment by JRMurr** [comment]
It looks like `joi.describe()` on this schema will give something like ```
"trueField": {
                "type": "string",
                "whens": [
                    {
                        "ref": {
                            "path": [
                                "type"
                            ]
                        },
                        "is": {
                            "type": "any",
                            "flags": {
                                "only": true,
                                "presence": "required"
                            },
                            "allow": [
                                {
                                    "override": true
                                },
                                true
                            ]
                        },
                        "then": {
                            "type": "any",
                            "flags": {
                                "presence": "required"
                            }
                        },
                        "otherwise": {
                            "type": "any",
                            "flags": {
                                "presence": "forbidden"
                            }
                        }
                    }
                ]
            },```

So while it is not pretty I think i can make something work. 

If your worried this could lead to bugs I can hide this behind a setting so we only go down this path if the user tells us too

**Comment by mrjono1** [comment]
we have lots of tests 😃  I'm not worried see what you can figure out 👍

**Comment by mrjono1** [comment]
I can do a beta release if you want to test it in your projects if that helps

**Comment by JRMurr** [comment]
Lol that would be dope. I'll sanitize some of our schemas and use them in tests too

**Comment by JRMurr** [comment]
@mrjono1 somewhat unrelated, would you be ok with adding something like lodash as a dependency? It has a lot of nice util functions that i could see being useful when i work on this

**Comment by mrjono1** [comment]
Im hoping to stay away from packages like lodash as a lot of it is becoming part of JavaScript, and to reduce the dependencies.
There was a package of helper functions when joi was part of @hapi i wonder if they are available for joi? @hapi/hoek i think it was

**Comment by JRMurr** [comment]
Hoek looks like it would cover most of the use cases i need and seems to be a dependent of joi so ill give that a shot

**Comment by JRMurr** [comment]
Worked on this a bit but got distracted by the holidays. We probably wont be able to support as much as i would like. We will most likely only be able to support the case when all conditions have `joi.valid` on them. Without negation types in ts more general conditions cause too many issues.

With that said, i would still like to support it with the `joi.valid` since this way of writing conditional types seems simpler to me then a big `joi.alternative`

**Comment by mrjono1** [comment]
`joi.valid()` is currently supported for values so extending that to types can be done see `__test__/enums.ts`

**Comment by mrjono1** [comment]
@JRMurr have you had any luck on this one?

I have a few ideas or steps
1. is the property required or optional based on the when
2. make a list of all the types base in the when

We could just start with a when being an optional any type

**Comment by mrjono1** [comment]
Closing for now, if this has more interest one day we can look again. @JRMurr feel free to raise a PR even if you have something basic
