### ISSUE TITLE
Can't disable the `index.ts` file

### ISSUE THREAD

**Issue by Oliver-Akins** [mrjono1/joi-to-typescript#260]
I'm trying to set this up for a project I'm working on, and it's working great, minus that it seems like the `indexAllToRoot` option is non-functional, no matter what I set it to, it outputs an `index.ts` file in the interfaces route.

Project Structure
```
makefile
generateInterfaces.ts
src:
    schemas:
        config.ts
    types:
```

What I want to be generated:
```
makefile
generateInterfaces.ts
src:
    schemas:
        config.ts
    types:
        config.ts
```

Versus what actually gets generated:
```
makefile
generateInterfaces.ts
src:
    schemas:
        config.ts
    types:
        config.ts
        index.ts
```

This isn't really blocking my project because I just added an additional command to my `makefile` to delete the `index.ts` for now, however it would be nice if the option did what it was claiming to do? (or maybe had a better description if I'm misunderstanding what it does)

Files:
```ts
// generateInterfaces.ts
import { convertFromDirectory } from "joi-to-typescript";

convertFromDirectory({
	indentationChacters: `\t`,
	schemaDirectory: "./src/schemas",
	typeOutputDirectory: "./src/types",
	treatDefaultedOptionalAsRequired: true,
	indexAllToRoot: false,
	fileHeader: `/*
This file was automatically generated by joi-to-typescript
Do not modify this file manually
*/`
});
```
```ts
// src/schemas/config.ts
import Joi from "joi";

export const serverOptionsSchema = Joi.object({
	port: Joi.number().port().description(`The port the server will run on`),
}).description(`The options specific to the web server`);

export const configSchema = Joi.object({
	server: serverOptionsSchema,
}).description(`The configuration format for the server`);
```
```make
# makefile
NODE = node
PACKAGE_MANAGER = pnpm
OUT_DIR = dist

BIN := $(shell $(PACKAGE_MANAGER) bin)

.PHONY: $(OUT_DIR) dev prod run


$(OUT_DIR): interfaces
	tsc --outDir=$(OUT_DIR)

interfaces:
	$(BIN)/ts-node generateInterfaces.ts
	rm src/types/index.ts
```
---

Environment information:
- Node v16.16.0
- Package manager: PNPM (version 7.9.0)
- Typescript 4.7.4
- Operating System: Ubuntu 20.04 LTS

---

If there's any extra information required let me know and I'll happily provide it.

**Comment by mrjono1** [comment]
This is way to late to comment.
The indexAllToRoot is for projects that have lots of sub directories with schemas.
I think your current solution is the best way to go
