### ISSUE TITLE
.rename() and .xor() schema methods are ignored

### ISSUE THREAD

**Issue by D10f** [mrjono1/joi-to-typescript#267]
**OS**: Linux pop-os 5.19.0-76051900-generic
**Node**: v16.17.0
**Joi**: 17.6.0
**Joi-to-typescript**: 4.0.5

Hi there,

I have the following schema which is intended to require only one of the keys described in `.xor()`, throwing an error if neither one or both are present in the object. Additionally, if the key provided was the one suffixed with "_FILE", it should be renamed to remove that suffix.

```ts
const ConfigSchema = Joi.object({
  JWT_SECRET: Joi.string(),
  JWT_SECRET_FILE: Joi.string(),
  MONGODB_NAME: Joi.string(),
  MONGODB_NAME_FILE: Joi.string()
})
  .xor('JWT_SECRET_FILE', 'JWT_SECRET')
  .xor('MONGODB_NAME_FILE', 'MONGODB_NAME')
  .rename('JWT_SECRET_FILE', 'JWT_SECRET')
  .rename('MONGODB_NAME_FILE', 'MONGODB_NAME')
```

This works fine at runtime, and I can write a TypeScript interface to work with the validated schema exactly as I intend to through the rest of my code:

```ts
export interface IConfig {
  JWT_SECRET: string;
  MONGODB_NAME: string;
}
```

However, when I use joi-to-typescript the resulting interface contains the properties that I need to remove as well:

```ts
export interface IConfig {
  JWT_SECRET: string;
  JWT_SECRET_FILE: string;
  MONGODB_NAME: string;
  MONGODB_NAME_FILE: string;
}
```
Is a missing feature of joi-to-typescript? Or perhaps I'm not using Joi's `.xor()` and `.rename()` methods properly (although they seem to work fine)? For reference, I have setup an npm script to run joi-to-typescript as follows (as I do not have ts-node installed globally):
```json
"scripts": {
  "types": "node_modules/.bin/ts-node src/schemas/types.ts"
}
```
```ts
// src/schemas/types.ts

import { convertFromDirectory } from 'joi-to-typescript';

convertFromDirectory({
  schemaDirectory: './src/schemas',
  typeOutputDirectory: './src/interfaces',
  defaultToRequired: true,
  ignoreFiles: ['types.ts'],
  debug: true
});
```

**Comment by D10f** [comment]
For reference to other readers, there's another approach to solve my issue using a different syntax:

```ts
export const ConfigSchema = Joi.object({
  JWT_SECRET: Joi.string().required().when('JWT_SECRET_FILE', {
    is: Joi.exist(),
    then: Joi.forbidden()
  }),
  MONGODB_NAME: Joi.string().required().when('MONGODB_NAME_FILE', {
    is: Joi.exist(),
    then: Joi.forbidden()
  })
})
```

The only problem with this is that if I provide both mutually exclusive keys by mistake, the error message is a bit misleading: "JWT_SECRET is not allowed". It could probably be fixed with additional code that I would rather avoid to type (which is the point of using joi-to-typescript)

**Comment by mrjono1** [comment]
I haven't tried `xor` or `rename` before, I'm glad you were able to solve the issue another way.

If you want to look how joi-to-typescript works you can run `.describe()` on your schema and see what comes out that is what I base the code generation on

**Comment by D10f** [comment]
Hi, and thank you for the tip I will have to take some time to look into it and see if I can somehow improve it. But for now I'll stick with the workaround that I found as it's virtually just as effective. I'll be closing this issue for now, cheers!
