### ISSUE TITLE
Joi.link syntax is not supported

### ISSUE THREAD

**Issue by wangshijun** [mrjono1/joi-to-typescript#281]
Joi supports link to create nested schema: https://joi.dev/api/?v=17.7.0#linkref

But seems this tool does not support it.

**Comment by mrjono1** [comment]
I have looked into Link, I am not looking to support this feature, I would suggest splitting up the schema into smaller schemas and reference them instead

**Comment by yegortokmakov** [comment]
What about cases where schema self-references?

```
const person = Joi.object({
  firstName: Joi.string().required(),
  lastName: Joi.string().required(),
  friends: Joi.array().items(Joi.link('#person'))
}).id('person');
```

**Comment by cur3n4** [comment]
I believe this is an option for self-references:
`
const person = Joi.object({
  firstName: Joi.string().required(),
  lastName: Joi.string().required(),
  friends: Joi.array().items(Joi.link('#person').meta({ className:'Person' })
}).id('person').meta({ className:'Person' });`

**Comment by mrjono1** [comment]
Yes this should work
