### ISSUE TITLE
support for alternatives.conditional

### ISSUE THREAD

**Issue by gaurav5430** [mrjono1/joi-to-typescript#301]
Could not find any tests / examples for alternatives.conditional.

This is what I am using

```
SomeSchema = joi
  .object({
    label: joi.string(),
    someid: joi.alternatives().conditional('label', {
      is: 'abc',
      then: joi.string().hex().required().length(24),
      otherwise: joi.forbidden(),
    }),
  })
  .meta({ className: 'SomeSchema' });
```

This is failing with 

`Cannot read property 'flags' of undefined`

**Comment by gaurav5430** [comment]
This seems to happen because when using conditionals in the above example, there is no `match.schema` generated

**Comment by gaurav5430** [comment]
it seems we don't support the is / then / otherwise clauses anywhere in the code for now. Would it be ok if we replace the conditional type with unknown for the time being? 

Something like this in parseAlternatives:

```
if(match.schema) return parseSchema(match.schema, settings, true, ignoreLabels);

return parseSchema({ type: undefined }, settings, true, ignoreLabels);
 ```

**Comment by mrjono1** [comment]
I had a quick look at the code and it looks like I am missing some undefined checks in the code which may also resolve the issue you are facing

**Comment by mrjono1** [comment]
I'm very happy for a pull request

**Comment by gaurav5430** [comment]
As per my limited understanding of the codebase; to ignore any matches which don't have schema,  we can do: 

1. `if(!match.schema) return parseSchema({ type: undefined }, settings, true, ignoreLabels );` . This will return "unknown" for the parent type
2. `if(!match.schema) return parseSchema({ type: "any" }, settings, true, ignoreLabels );` . This will return "any" for the parent type
3. `if(!match.schema) return undefined` . This will skip the parent type from the generated types

What would you prefer? I would prefer option 1, to return "unknown" for the parent type.

**Comment by gaurav5430** [comment]
ohk, it seems option 1 is not possible because 'undefined' is not a joi type we support. 

I can either `ts-ignore` and pass { type: undefined } 
OR pass { type: undefined } as unknown as Describe to make ts happy, but both of them are confusing enough. 

Also, i see that in other places in the codebase, you are using "any" as the default fallback type, so i would use "any" here as well.
