### ISSUE TITLE
Conversion not respecting Joi sparse array and including undefined in type

### ISSUE THREAD

**Issue by ludu12** [mrjono1/joi-to-typescript#324]
**Describe the bug**
When defining an array schema, the `sparse` schema method does not produce the correct type. We cannot get `undefined` to be a valid type within an array.

**To Reproduce**

```TypeScript
import Joi from 'joi';
import {convertSchema} from 'joi-to-typescript';

const mySchema = Joi.array().items(Joi.string().allow(null, '')).sparse().meta({className: 'MySchema'})

// Passes validation
// { value: [ '', 'string', null, undefined ] }
const validation = mySchema.validate(['', 'string', null, undefined])
console.log(validation)

// Does not have the correct type
// export type MySchema = (string | null | '')[];
const result = convertSchema({}, mySchema)
console.log(result?.content)
```

**Expected behavior**
```TypeScript
export type MySchema = (string | null | '' | undefined)[];
```

**Actual behavior**
```TypeScript
export type MySchema = (string | null | '')[];

```

**Additional context**
Perhaps there is a different way to achieve what we're trying to get.

**Comment by mrjono1** [comment]
I'm not at my computer at the moment, can you try adding `.optional()`? it may help
```typescript
const mySchema = Joi.array().items(Joi.string().allow(null, '').optional()).sparse().meta({className: 'MySchema'})
```

**Comment by mrjono1** [comment]
does it work without `.sparse()`? I haven't used that before

**Comment by ludu12** [comment]
> I'm not at my computer at the moment, can you try adding `.optional()`? it may help
> 
> ```ts
> const mySchema = Joi.array().items(Joi.string().allow(null, '').optional()).sparse().meta({className: 'MySchema'})
> ```

so `.optional()` does not work either:

```ts
const mySchema = Joi.array().items(Joi.string().allow(null, '').optional()).sparse().meta({className: 'MySchema'})
const result = convertSchema({}, mySchema)

// export type MySchema = (string | null | '')[];
console.log(result?.content)
```

If I don't include `.sparse()` then the following array:

```ts
const validation = mySchema.validate(['', 'string', null, undefined])
```

will fail

**Comment by mrjono1** [comment]
I'll need to look into what Joi.describe() produces for this. I'm suspecting it may have a bug???
