### ISSUE TITLE
converting to .default() doesn't make sense

### ISSUE THREAD

**Issue by qraxiss** [mrjono1/joi-to-typescript#355]
**Describe the bug**
x.default() -> x?

i think it doesn't make sense, because default always defined

**Comment by mrjono1** [comment]
At the moment everything is default to optional, yes making this to required by default would be better.

as a workaround you can do 2 things
use the `defaultToRequired` setting or `.requried()`

**Comment by qraxiss** [comment]
when i use  .default().required(), field cannot empty

**Comment by mrjono1** [comment]
I think you need to set what the default value is

**Comment by qraxiss** [comment]
https://github.com/hapijs/joi/issues/2973#event-10095896576
