### ISSUE TITLE
Cannot generate an error-free type with known and unknown keys with different values

### ISSUE THREAD

**Issue by CMunkyDev** [mrjono1/joi-to-typescript#470]
**Describe the bug**
Cannot generate an error-free type with known and unknown keys with different values

**To Reproduce**
`ExampleSchema.ts`
```TypeScript
import * as Joi from "joi"

export const examplesSchema = Joi.object({
    knownKey: Joi.string(),
})
.unknown(true)
.meta({ className: "Example", unknownType: Joi.object() })
```

**Expected behavior**
A generated type without errors

```TypeScript
export type Example = {
    [x: string]: object;
} & {
    knownKey?: string;
}
// or
export interface Example {
    [x: string]: typeof x extends 'knownKey' ? string : object;
}
```

**Actual behavior**
Generated type has errors
```TypeScript
export interface Example {
  [x: string]: object;
  knownKey?: string;
}
```
![image](https://github.com/user-attachments/assets/323416d9-7e8d-43bc-847a-f17bd7081217)
**Additional context**
It's not 100% necessary, and maybe there's a better way, but when you have a known key with a certain value type, and an unknown key that would have a different value type, I'm not seeing how I could write a Joi schema in a way that would get `joi-to-typescript` to make a type without errors.

For now, I've written a little helper that runs after `convertFromDirectory` to add a `@ts-expect-error` on the line above the offending line, as it seems typescript still works fine and VS Code suggests the right stuff; but that's definitely only a temporary solution. I might be able to make a PR but figured I'd put this issue in.

please let me know if I'm just being silly. Thanks!

**Comment by mrjono1** [comment]
```typescript
import * as Joi from "joi"

export const examplesSchema = Joi.object({
  // I think you need required here
    knownKey: Joi.string().required(),
})
.unknown(true)
.meta({ className: "Example", unknownType: Joi.object() })
```
