### ISSUE TITLE
Handle unsupported Joi types by making them `any`

### ISSUE THREAD

**Issue by JRMurr** [mrjono1/joi-to-typescript#5]
This way Ts wouldn't error if they still try to use a valid joi object

**Comment by mrjono1** [comment]
@JRMurr the latest release now supports 
```Joi.object({
prop: Joi.object() //<-- does this perform enough?
}).label('Test')

**Comment by JRMurr** [comment]
@mrjono1 This mostly was to handle this case here https://github.com/mrjono1/joi-to-typescript/blob/f5932ae2fc6fcb5cd6c2d1d24706fd45a141894c/src/parse.ts#L202. Honestly not sure how used the few joi types we don't support are so probably not a big deal if you want this closed

**Comment by mrjono1** [comment]
I'll close the issue, if someone has an example of an issue Ill work on it
