### ISSUE TITLE
Using valid or allow on Joi.number() does not produce a number typed field

### ISSUE THREAD

**Issue by adam-charlton** [mrjono1/joi-to-typescript#54]
When generating a schema with a `Joi.number()` that has `valid()` or `allow()` the resulting type is not a number but assumed the valid values as the types of the field.

**To Reproduce**
```typescript
export const TestSchema = Joi.object({
  'clean': Joi.number(),
  'valid': Joi.number().valid(0, 1),
  'allow': Joi.number().allow(2, 3)
}).label('Test');
```

**Expected behavior**
```typescript
export interface Test {
  allow?: number;
  clean?: number;
  valid?: number;
}
```

**Actual behavior**
```typescript
export interface Test {
  allow?: 2 | 3;
  clean?: number;
  valid?: 0 | 1;
}
```

**Comment by mrjono1** [comment]
This is actually the designed behavior, as per your joi only 2 numbers can be assigned to these properties
