### ISSUE TITLE
Allow null doesn't work on array and object

### ISSUE THREAD

**Issue by ntta** [mrjono1/joi-to-typescript#77]
Hi,

I'm not sure if you guys are aware of this issue/bug.

Joi:
`name: Joi.string().allow(null).required`

TypeScript:
`name: string | null`

This result is correct. However, when I use it with the array type, it doesn't generate | null

Joi:
`imageUrls: Joi.array().items(Joi.string()).allow(null).required()`

TypeScript:
`imageUrls: string[]`

It's supposed to be `imageUrls: string[] | null`
The same issue with object.

**Comment by mrjono1** [comment]
Thanks for the issue, this does look like a bug

**Comment by RatTac** [comment]
Having the exact same problem. allow(null) works fine on string but it is just ignored for object types...
A fix would be great ;)
Great work on the package!

**Comment by mrjono1** [comment]
I've made a start, progress on objects but not on arrays yet

**Comment by RatTac** [comment]
@mrjono1: Brilliant! Thx for the update, will prevent me from having to implement an ugly workaround by manually having to overwrite the generated interfaces ;)

**Comment by mrjono1** [comment]
https://github.com/mrjono1/joi-to-typescript/pull/86 I made some more progress :)

**Comment by RatTac** [comment]
Perfect, this looks great! Thanks a lot!
Any plans when this change will be pushed to the npm registry?

**Comment by mrjono1** [comment]
working on it now :)

**Comment by mrjono1** [comment]
version 1.12.0 has been released

**Comment by RatTac** [comment]
@mrjono1: Unfortunately I'm still having issues with the updated version. Can you confirm this on the following example?

Input:
```
export const childSchema = Joi.object({
	item: Joi.number()
		.required()
		.example(0),
}).label("Child");

export const parentSchema = Joi.object({
	child: childSchema.allow(null).required(),
}).label("Parent");
```

Output:
```
export interface Child {
  item: number;
}

export interface Parent {
  child: Child;
}
```

I would expect: 
```
export interface Parent {
  child: Child | null;
}
```

**Comment by mrjono1** [comment]
https://github.com/mrjono1/joi-to-typescript/pull/93

**Comment by RatTac** [comment]
@mrjono1: Works, thx!
