### ISSUE TITLE
Clear output directory

### ISSUE THREAD

**Issue by mrjono1** [mrjono1/joi-to-typescript#8]
Add an option to clear the `typeOutputDirectory` to ensure there is no junk files

**Comment by mrjono1** [comment]
looks super easy, something like this with an option
```import {  rmdirSync } from 'fs';

rmdirSync(typeOutputDirectory, { recursive: true });```

**Comment by Aniket1026** [comment]
Does this issue is still open ?

**Comment by mrjono1** [comment]
This is still open, I am open to PRs to add this feature

**Comment by Aniket1026** [comment]
Sure   I'll start working 👍

**Comment by Aniket1026** [comment]
sorry for bothering you, I just wanna know when does these typeOutputDirectory are actually being created?

I tried using it with joi to understand how it works , i followed the provided examples but I was facing some errors while running it on my windows10 machine
