### ISSUE TITLE
feat: add ignoreFiles patterns (and ignore tests files by default)

### ISSUE THREAD

**Issue by Toub** [mrjono1/joi-to-typescript#81]
Unit test files should be excluded from interfaces generation (ideally, by default in a future major version).

To avoid listing all of them, what about adding file patterns support to `excludeFiles` option (e.g. `['**/*.test.ts`', '**/*.spec.ts`']) or adding a separate `excludeFilesPatterns` option to support patterns or regexp ?

Also, a similar `includeFiles` option (matching patterns) would be useful!

**Comment by mrjono1** [comment]
Hi @Toub this sounds like a good enhancement, I probably wont get around to implementing this, but I am very open to a PR on this

**Comment by mrjono1** [comment]
This issue is also being talked about here https://github.com/mrjono1/joi-to-typescript/issues/133 and looks to be progressing it with a PR so I'm closing this issue
