### ISSUE TITLE
Error exporting primitive types from schema file root

### ISSUE THREAD

**Issue by thiagozf** [mrjono1/joi-to-typescript#85]
When exporting a labeled Joi schema that results in a primitive TypeScript type, `joi-to-typescript` generates an invalid output. This pattern is very useful when you want to reuse Joi schemas (e.g. an `EmailSchema` can be used by both `UserSchema` and `CompanySchema`).

## To reproduce
```typescript
export const EmailSchema = Joi.string()
  .email({ tlds: { allow: false } })
  .label('Email')

export const CompanySchema = Joi.object({
  email: EmailSchema
})

export const UserSchema = Joi.object({
  email: EmailSchema.required()
})
```

## Expected behaviour
```typescript
/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export type Email = string

export type Company = {
  email?: Email
}

export type User = {
  email: Email
}
```

## Actual behaviour
```typescript
/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

string // Here is the issue, should be (type Email = string)

export type Company = {
  email?: Email
}

export type User = {
  email: Email
}
```

**Comment by mrjono1** [comment]
I hadn't originally considered this use case but after pointing it out it is valid

**Comment by mrjono1** [comment]
https://github.com/mrjono1/joi-to-typescript/tree/primitive-types made a bit of progress here
Got string primitive working, still need to get the other types going

**Comment by mrjono1** [comment]
I have released a fix for this https://github.com/mrjono1/joi-to-typescript/releases/tag/1.14.0
