### ISSUE TITLE
Labels with spaces produce invalid type names

### ISSUE THREAD

**Issue by AverageHelper** [mrjono1/joi-to-typescript#98]
With this schema:

```TypeScript
export const RegisterAccountParams = Joi.object({
  name: Joi.string()
    .label("Company Name")
    .required(),
  phoneNumber: Joi.string()
    .label("Company Phone Number")
    .required(),
  customerEmail: Joi.string()
    .label("Customer Email")
    .required(),
  website: Joi.string()
    .label("Website")
});
```

this output is generated:

```TypeScript
/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { Customer Email, Company Name, Company Phone Number, Website } from '.';

export interface RegisterAccountParams {
  customerEmail: Customer Email;
  name: Company Name;
  phoneNumber: Company Phone Number;
  website?: Website;
}
```

The import statement is clearly incorrect. It seems to me that joi-to-typescript takes `label` to mean that we're referencing another named exported schema, which is not our intention.

Labels are handy for customizing the error messages that Joi throws on validation failures. Is there a way that this behaviour might be made configurable, or perhaps default to ignoring `label` modifiers on object properties?

To be clear, we expect an output similar to this one:

```TypeScript
export interface RegisterAccountParams {
  customerEmail: string;
  name: string;
  phoneNumber: string;
  website?: string;
}
```

**Comment by mrjono1** [comment]
Labels are an integral part how this library works. I am using label so this library will work with hapi-swagger.

I would like to swap from label() to id() but im not sure if that is even possible.

If you can I suggest swapping from label() to description()

**Comment by AverageHelper** [comment]
Unfortunately, `description` will not work for our use case. We use `label` for its effect on Joi's error output. `description` has no such behavior. Perhaps we should instead write a custom error handler to capitalize and transform our camelCase property names, rather than use `label`.

At any rate, for labeled properties in every case to output the `label` value in type positions seems like a bug, or perhaps a logical error. This behavior would make sense if the value for `label` matches a type name that has already been parsed. In other cases, such as when the `label` value contains spaces, this assumption does not hold, and this package generates invalid TypeScript.

Is there some compromise that can be made, perhaps either throwing an error if the `label` value contains spaces, or making this label behavior more configurable? Perhaps spaces should be ignored, and values transformed into CamelCase. I would be willing to structure my schemas differently to support a solution, especially if it preserves existing functionality.

For example, my case above already partially works in the case of the `website` property if I define and export a schema under the `Website` name, like so:

```TypeScript
export const Website = Joi.string()
  .label("Website");
```

This way, the `Website` schema still uses a capitalized name in the event of a `validate` error. I have tested this case; to export `Website` this way today generates a `Website` type as an alias to `string` and uses that as the type for the `website` optional property. This behavior is technically correct, and compiles, and so is acceptable to me.

The other properties' labels contain spaces, and therefore will not compile this way under the current version of joi-to-typescript.

If joi-to-typescript could be made to ignore or transform `label` modifiers that contain spaces, then the rest of the schema might be defined this way:

```TypeScript
export const CompanyName = Joi.string()
  .required()
  .label("Company Name");

export const CompanyPhoneNumber = Joi.string()
  .required()
  .label("Company Phone Number");

export const CustomerEmail = Joi.string()
  .required()
  .label("Customer Email");

export const RegisterAccountParams = Joi.object({
  name: CompanyName,
  phoneNumber: CompanyPhoneNumber,
  customerEmail: CustomerEmail,
  website: Website
});
```

This should allow the types to generate properly, albeit with some gratuitous type aliases to `string`

**Comment by mrjono1** [comment]
Hi @AverageHelper if you are interested in doing a Merge Request I can look at your idea further.

**Comment by AverageHelper** [comment]
#99 seems to work for my use case.

**Comment by mrjono1** [comment]
Cheers dude, I'll get this released

**Comment by mrjono1** [comment]
version 1.14.1 released, thank you for the contribution :)

This has made me think more about moving the label() options to id() especially for this type of use case
